import "./globals.css";
import { Inter } from "next/font/google";
import { Navigation } from "../components/navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Roar",
  description: `Generated by Roar's Developers`,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
